docker: 
  url: localhost
server: 
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.shqblog.entity   # entity·
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapperӳļ
  configuration:
#    mapUnderscoreToCamelCase: true        #  շ
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
spring:
  profiles: test
  application: 
    name: blog-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://${docker.url}:3306/pay
    username: root
    password: root
    dbcp2:
      min-idle: 5                     # ݿӳصСά
      initial-size: 5                  # ʼ
      max-total: 5                    # 
      max-wait-millis: 200            # ȴӻȡʱʱ
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:  #ͻעeurekaб
    service-url:
      defaultZone: http://${docker.url}:6731/eureka/
       #΢бעspring.application.name
  instance:
    instance-id: blog-pay:8001
    prefer-ip-address: true
  enabled: true
  register-with-eureka: true
  fetch-registry: true
info: 
  app.name: shablog
  company.name: www.shqblog.com
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
alipay: 
  serverUrl: https://openapi.alipay.com/gateway.do
  formatL: json
  charset: utf-8
  signType: RSA2
      
---
docker: 
  url: 172.17.251.66
server: 
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.shqblog.entity   # entity??????
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapper??????
  configuration:
#    mapUnderscoreToCamelCase: true       #  ?????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
spring:
  profiles: dev
  application: 
    name: blog-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://${docker.url}:3306/pay
    username: root
    password: qq183521065
    dbcp2:
      min-idle: 5                     # ??????????????????????
      initial-size: 5                 # ???????????
      max-total: 5                    # ?????????
      max-wait-millis: 200            # ??????????????????
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client: #?????????eureka????????
    service-url:
      defaultZone: http://${docker.url}:6731/eureka/
      #?????????????????????spring.application.name??????
  instance:
    instance-id: blog-pay:8001
    prefer-ip-address: true
  enabled: true
  register-with-eureka: true
  fetch-registry: true
info: 
  app.name: shablog
  company.name: www.shqblog.com
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
alipay: 
  serverUrl: https://openapi.alipay.com/gateway.do
  formatL: json
  charset: utf-8
  signType: RSA2
      