server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.shqblog.entity   # entity·
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapperӳļ
  configuration:
#    mapUnderscoreToCamelCase: true       #  շ
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
spring:
  profiles: dev
  application: 
    name: blog-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: root
    dbcp2:
      min-idle: 5                     # ݿӳصСά
      initial-size: 5                 # ʼ
      max-total: 5                    # 
      max-wait-millis: 200            # ȴӻȡʱʱ
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: false
eureka:
  client: #ͻעeurekaб
    service-url:
      defaultZone: http://localhost:6731/eureka/
      #΢бעspring.application.name
  instance:
    instance-id: blog-pay:8001
    prefer-ip-address: true
info: 
  app.name: shablog
  company.name: www.shqblog.com
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
alipay: 
  serverUrl: https://openapi.alipaydev.com/gateway.do
  formatL: json
  charset: utf-8
  signType: RSA2