server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.shqblog.entity   # entity所在路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml    # mapper映射文件
  configuration:
#    mapUnderscoreToCamelCase: true       #  开启驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
spring:
  profiles: dev
  application: 
    name: blog-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: root
    dbcp2:
      min-idle: 5                     # 数据库连接池的最小维持连接数
      initial-size: 5                 # 初始化连接数
      max-total: 5                    # 最大连接数
      max-wait-millis: 200            # 等待连接获取的最大超时时间
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client: #客户端注册金eureka服务列表中
    service-url:
      defaultZone: http://127.0.0.1:6731/eureka/
      #在微服务列表中注册的名字是spring.application.name的名字
  instance:
    instance-id: blog-pay:8001
    prefer-ip-address: true
  enabled: true
  register-with-eureka: true
  fetch-registry: true
info: 
  app.name: shablog
  company.name: www.shqblog.com
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
alipay: 
  serverUrl: https://openapi.alipaydev.com/gateway.do
  formatL: json
  charset: utf-8
  signType: RSA2